name: e_commerce
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

#---Packages----#

dependencies:
  flutter:
    sdk: flutter

  #Utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  curved_navigation_bar: ^1.0.5

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #state management
  get: ^4.6.5
  get_storage: ^2.1.1

  #Product specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  #Firebase
  firebase_core: ^2.31.1
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.5
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.7
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3




#----Packages end----#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Local assets:
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/products/
    - assets/images/banners/
    - assets/images/user/
    - assets/images/reviews/
    - assets/images/products/nike/
    - assets/images/products/adidas/
    - assets/images/products/mvc/
    - assets/images/products/puma/
    - assets/images/products/zara/

  #local font
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800